### ISSUE TITLE
:help not recognised when followed by a full stop

### ISSUE THREAD

**Issue by puremourning** [heraldofsolace/VimHelpBot#11]
**Describe the bug**

https://www.reddit.com/r/vim/comments/h7fpdr/introduction_and_tip_on_switching_from_terminal/fuksrpj?utm_source=share&utm_medium=web2x

In this comment I wrote `:help terminal-typing.` The full stop ends the sentence and isn't part of the help tag. It seems the bot didn't find that tag.

**To Reproduce**
1. Comment `:help terminal-typing.`

**Expected behavior**

The wonderful awesome bot adds a link to the help for `terminal-typing`

**Screenshots**
https://www.reddit.com/r/vim/comments/h7fpdr/introduction_and_tip_on_switching_from_terminal/fuksrpj?utm_source=share&utm_medium=web2x

[X] Willing to take up?

**Comment by Herald-Of-Solace** [comment]
The problem is that the trailing period is a valid character, and quite a few tags have a trailing period (e. g. `quote.`). Also, a large number of tags have period in the middle, so that it's a viable candidate for partial search. So we can't strip the period away.

We could do one thing so that if we get an exact match without a period and no match with a period, we can strip the period away.

It's best to use backticks and format the query as quote. That way the bot can unambiguously distinguish between the queries and the texts.

**Comment by jakergrossman** [comment]
Is there still any interest for this? It seems like you've laid out the solution:

If a space-style regex match ends in some subset of punctuation characters (which ones?), but does not find a tag, check again with the punctuation removed.
